---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data
  namespace: my-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/cassandra
