---
apiVersion: batch/v1
kind: Job
metadata:
  name: createbucket
  namespace: my-app
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: createbucket
          image: minio/mc:RELEASE.2023-07-11T23-30-44Z
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: prod-config
                  key: MINIO_ROOT_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              /usr/bin/mc config host add myminio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
              /usr/bin/mc mb myminio/myfilebucket;
              /usr/bin/mc anonymous set private myminio/myfilebucket;
