---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: chat-backend
          image: forkbikash/chat-api:kafka
          command: ["chat"]
          ports:
            - containerPort: 80
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  namespace: my-app
spec:
  selector:
    app: chat-backend
  ports:
    - port: 80
      targetPort: 80
    - port: 4000
      targetPort: 4000
