---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.22
          ports:
            - containerPort: 14268
            - containerPort: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: my-app
spec:
  selector:
    app: jaeger
  ports:
    - port: 14268
      targetPort: 14268
    - port: 16686
      targetPort: 16686
