---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
        - name: match
          image: forkbikash/chat-api:kafka
          command: ["match"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: match
  namespace: my-app
spec:
  selector:
    app: match
  ports:
    - port: 80
      targetPort: 80
