---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2023-07-11T21-29-34Z
          ports:
            - containerPort: 9000
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: minio-root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: minio-root-password
            - name: MINIO_API_ROOT_ACCESS
              value: "on"
            - name: MINIO_SERVER_URL
              value: "http://minio:9000"
          args:
            - server
            - /export
            - --console-address
            - ":9001"
          volumeMounts:
            - name: data
              mountPath: /export
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: my-app
spec:
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
    - port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: my-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
