---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: forkbikash/chat-reverse-proxy:kafka
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: keys
              mountPath: /etc/ssl/private
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: tls-secret
        - name: keys
          secret:
            secretName: tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  namespace: my-app
spec:
  selector:
    app: reverse-proxy
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  type: LoadBalancer
