---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: forkbikash/chat-api:kafka
          command: ["user"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: my-app
spec:
  selector:
    app: user
  ports:
    - port: 80
      targetPort: 80
